/* ══════════════════════════════════════════════════════════════
   RBAC — Estilos compartilhados (mesmo design system)
   ══════════════════════════════════════════════════════════════ */

const S = {
  /* ── Card ─────────────────────────────────────── */
  card: {
    background: "#fff",
    borderRadius: "16px",
    border: "1px solid #f1f5f9",
    padding: "24px",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "18px",
    flexWrap: "wrap",
    gap: "12px",
  },
  cardTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  cardIcon: {
    display: "flex",
    color: "#94a3b8",
  },
  cardTitle: {
    margin: 0,
    fontSize: "15px",
    fontWeight: "600",
    color: "#0f172a",
    letterSpacing: "-0.01em",
  },

  /* ── Botões ───────────────────────────────────── */
  btnPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    border: "none",
    borderRadius: "10px",
    padding: "9px 18px",
    background: "#2563eb",
    color: "#fff",
    fontWeight: "600",
    fontSize: "13px",
    cursor: "pointer",
    boxShadow: "0 1px 3px rgba(37,99,235,0.2)",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    height: "38px",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  btnSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #e2e8f0",
    borderRadius: "10px",
    padding: "8px 16px",
    background: "#fff",
    color: "#334155",
    fontWeight: "500",
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
    height: "38px",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  btnDanger: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #fecaca",
    borderRadius: "10px",
    padding: "8px 16px",
    background: "#fef2f2",
    color: "#dc2626",
    fontWeight: "500",
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
    height: "38px",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },

  /* ── Tabela ───────────────────────────────────── */
  tableWrap: {
    overflowX: "auto",
    borderRadius: "12px",
    border: "1px solid #f1f5f9",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
  },
  th: {
    padding: "12px 16px",
    textAlign: "left",
    fontSize: "11px",
    fontWeight: "600",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    background: "#fafbfc",
    borderBottom: "1px solid #f1f5f9",
  },
  td: {
    padding: "12px 16px",
    borderBottom: "1px solid #f8fafc",
    color: "#0f172a",
    fontWeight: "500",
  },
  tr: {
    transition: "background 0.1s ease",
  },

  /* ── Checkbox de permissão ─────────────────────── */
  permCheckbox: {
    width: "22px",
    height: "22px",
    borderRadius: "6px",
    border: "2px solid #d1d5db",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.15s ease",
    padding: 0,
    fontFamily: "inherit",
  },

  /* ── Role Select Button ────────────────────────── */
  roleSelectBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    background: "#fff",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.15s ease",
    fontFamily: "inherit",
  },
  roleDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    flexShrink: 0,
  },

  /* ── Role Card ─────────────────────────────────── */
  roleCard: {
    background: "#fff",
    borderRadius: "12px",
    border: "1px solid #f1f5f9",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    transition: "all 0.15s ease",
  },
  roleCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  roleCardInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  roleCardDot: {
    width: "14px",
    height: "14px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  roleCardName: {
    fontSize: "15px",
    fontWeight: "600",
    color: "#0f172a",
  },
  roleCardDesc: {
    fontSize: "13px",
    color: "#64748b",
    lineHeight: 1.5,
  },
  roleCardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "12px",
    borderTop: "1px solid #f1f5f9",
  },
  roleCardBadge: {
    fontSize: "12px",
    fontWeight: "600",
    padding: "4px 10px",
    borderRadius: "6px",
    background: "#f0f4ff",
    color: "#2563eb",
  },

  /* ── Modal / Overlay ──────────────────────────── */
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(15, 23, 42, 0.5)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modal: {
    background: "#fff",
    borderRadius: "20px",
    width: "100%",
    maxWidth: "480px",
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 25px 60px rgba(15, 23, 42, 0.25)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 24px",
    borderBottom: "1px solid #f1f5f9",
  },
  modalTitle: {
    fontSize: "17px",
    fontWeight: "700",
    color: "#0f172a",
    margin: 0,
  },
  modalBody: {
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  modalFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "10px",
    padding: "16px 24px",
    borderTop: "1px solid #f1f5f9",
  },
  modalCloseBtn: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#94a3b8",
    display: "flex",
    padding: "4px",
    borderRadius: "8px",
    transition: "all 0.15s ease",
  },

  /* ── Formulário ───────────────────────────────── */
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#334155",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  input: {
    padding: "11px 14px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
    outline: "none",
    backgroundColor: "#fff",
    color: "#0f172a",
    fontWeight: "500",
    boxSizing: "border-box",
    transition: "all 0.2s ease",
    width: "100%",
    fontFamily: "inherit",
  },
  select: {
    padding: "11px 14px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
    outline: "none",
    backgroundColor: "#fff",
    color: "#0f172a",
    fontWeight: "500",
    boxSizing: "border-box",
    transition: "all 0.2s ease",
    width: "100%",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  textarea: {
    padding: "11px 14px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
    outline: "none",
    backgroundColor: "#fff",
    color: "#0f172a",
    fontWeight: "500",
    boxSizing: "border-box",
    transition: "all 0.2s ease",
    width: "100%",
    fontFamily: "inherit",
    resize: "vertical",
    minHeight: "80px",
  },

  /* ── Cores Picker ──────────────────────────────── */
  coresRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  corBtn: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "2px solid transparent",
    cursor: "pointer",
    transition: "all 0.15s ease",
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  /* ── Alertas ──────────────────────────────────── */
  alertaInfo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    borderRadius: "10px",
    padding: "12px 16px",
    fontSize: "13px",
    fontWeight: "500",
    border: "1px solid #bfdbfe",
    background: "#eff6ff",
    color: "#1d4ed8",
    marginBottom: "16px",
  },
  alertaErro: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    borderRadius: "10px",
    padding: "10px 14px",
    fontSize: "13px",
    fontWeight: "600",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#b91c1c",
  },
  alertaSucesso: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    borderRadius: "10px",
    padding: "10px 14px",
    fontSize: "13px",
    fontWeight: "600",
    border: "1px solid #dcfce7",
    background: "#f0fdf4",
    color: "#15803d",
  },

  /* ── Grids ─────────────────────────────────────── */
  rolesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "16px",
  },

  /* ── Badges ────────────────────────────────────── */
  protectedBadge: {
    fontSize: "10px",
    fontWeight: "700",
    padding: "3px 8px",
    borderRadius: "6px",
    background: "#fef3c7",
    color: "#b45309",
    border: "1px solid #fde68a",
  },

  /* ── Empty State ───────────────────────────────── */
  emptyState: {
    textAlign: "center",
    padding: "40px 20px",
    color: "#94a3b8",
    fontSize: "14px",
  },
};

export default S;